# Generated by Django 3.1.1 on 2020-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200912_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
