# Generated by Django 3.1.1 on 2020-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textbody',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
