# Generated by Django 3.1.1 on 2020-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_textbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liveViewCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=1),
        ),
    ]
