# Generated by Django 3.1.1 on 2020-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200913_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='projecturl',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
